name: Promote - Prod

on:
  release:
    types: [created]

jobs:
  promote:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: 'google-github-actions/auth@v2'
        id: auth
        with:
          project_id: 'dar-dev-02'
          workload_identity_provider: 'projects/998858198546/locations/global/workloadIdentityPools/github/providers/github-oidc'
          service_account: 'github-actions-default@dar-dev-02.iam.gserviceaccount.com'
          token_format: 'access_token'
          
      - name: Docker Auth
        id: docker-auth-dev
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: 'us-east4-docker.pkg.dev'

      - name: Docker Pull & Tag
        run: |
          docker pull us-east4-docker.pkg.dev/dar-dev-02/sui-staking-rewards/app:${{ steps.vars.outputs.sha_short }}
          docker tag us-east4-docker.pkg.dev/dar-dev-02/sui-staking-rewards/app:${{ steps.vars.outputs.sha_short }} us-docker.pkg.dev/dar-prod-01/sui-staking-rewards/app:${{ github.ref_name }}
          docker rmi us-east4-docker.pkg.dev/dar-dev-02/sui-staking-rewards/app:${{ steps.vars.outputs.sha_short }}
          docker tag us-docker.pkg.dev/dar-prod-01/sui-staking-rewards/app:${{ github.ref_name }} us-docker.pkg.dev/dar-prod-01/sui-staking-rewards/app:prod
          docker tag us-docker.pkg.dev/dar-prod-01/sui-staking-rewards/app:${{ github.ref_name }} us-docker.pkg.dev/dar-prod-01/sui-staking-rewards/app:${{ steps.vars.outputs.sha_short }}
      
      - uses: 'google-github-actions/auth@v2'
        id: auth-prod
        with:
            project_id: 'dar-prod-01'
            workload_identity_provider: 'projects/811845982766/locations/global/workloadIdentityPools/github/providers/-github-oidc'
            service_account: 'github-actions-default@dar-prod-01.iam.gserviceaccount.com'
            token_format: 'access_token'
            
      - name: Docker Auth
        id: docker-auth-prod
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth-prod.outputs.access_token }}'
          registry: 'us-docker.pkg.dev'

      - name: Push image - Prod
        run: docker push -a us-docker.pkg.dev/dar-prod-01/sui-staking-rewards/app